// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clone(arg1, arg2) {
  return window['go']['main']['App']['Clone'](arg1, arg2);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRepos() {
  return window['go']['main']['App']['GetRepos']();
}

export function GetStoragePath() {
  return window['go']['main']['App']['GetStoragePath']();
}

export function ListGithubRepos() {
  return window['go']['main']['App']['ListGithubRepos']();
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['main']['App']['Push'](arg1);
}

export function SaveRepos(arg1) {
  return window['go']['main']['App']['SaveRepos'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function ValidateAndSaveConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateAndSaveConfig'](arg1, arg2);
}
