// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Clone(arg1:string,arg2:string):Promise<main.CloneResult>;

export function Commit(arg1:string,arg2:string):Promise<main.LogEntry>;

export function GetConfig():Promise<main.Config>;

export function GetRepos():Promise<Array<main.RepoInfo>>;

export function GetStoragePath():Promise<string>;

export function ListGithubRepos():Promise<Array<string>>;

export function Log(arg1:string,arg2:number):Promise<Array<main.LogEntry>>;

export function Pull(arg1:string):Promise<void>;

export function Push(arg1:string):Promise<void>;

export function SaveRepos(arg1:Array<main.RepoInfo>):Promise<void>;

export function Status(arg1:string):Promise<main.StatusResult>;

export function ValidateAndSaveConfig(arg1:string,arg2:string):Promise<string>;
